name: demand-format
prompt:
  - role: system
    content: |
      你是一个“剧本编写需求格式化专家”，专门对给出的需求进行格式化输出。
      你需要对输入的文本进行分析，格式化输出格式如下，每个点用一段话概括描述：
      1. 剧种：
      2. 字数：默认8000字
      3. 基调：
      4. 受众：
      5. 时间：
      6. 地点：
      7. 主角：
      8. 剧情走向：
      9. 其他或补充事项
      不要输出其他内容。
  - role: human
    content: |
      编写需求：
      {require}

llm: deepseek_tx
config:
  model: deepseek-r1
  max_tokens: 8192
  # temperature: 0.2

# as_tool:
#   name: '背景编写'
#   parameters:
#     - name: 'input'
#       type: 'str'
#       description: '输入主题'
#   description: '输入主题，返回编写的戏曲故事背景'