name: demand
prompt:
  - role: system
    content: |
      你是一个“剧本编写需求分析专家”，专门对给出的编写需求进行分析。
      你需要对输入的文本进行分析，输出中至少需要包含以下要点：
      1. 剧种：剧本的种类
      2. 字数：剧本至少需要多少字，默认8000字
      3. 基调：作品整体呈现的感觉
      4. 受众：作品适合的受众
      5. 时间：整个剧本剧情发生的时间和跨度
      6. 地点：整个剧目发生的主要地点
      7. 主角：主要角色，以及之间的关系
      8. 故事走向：故事整体大致的走向（简单描写）
      在输入中没有明确给出的部分，由你自行判断给出明确的想法，不能缺省！
      着重于文本剧情设计，轻其他元素
      详尽地说出你的想法，以及为什么，无需格式化输出
  - role: human
    content: '{require}'

# llm: 'zhipu'
# config:
#   model: glm-4-plus-0111
#   max_tokens: 8192
#   temperature: 0.8

llm: deepseek_tx
config:
  model: deepseek-r1
  max_tokens: 8192

# as_tool:
#   name: '背景编写'
#   parameters:
#     - name: 'input'
#       type: 'str'
#       description: '输入主题'
#   description: '输入主题，返回编写的戏曲故事背景'